name: RDP Server Deployment (Production)

on:
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run even if another instance is running'
        required: false
        default: 'false'

jobs:
  deploy-rdp:
    runs-on: windows-latest
    timeout-minutes: 90
    permissions:
      contents: write  # Required to push connection details back to repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: System Information and Prerequisites
      run: |
        echo "=== SYSTEM INFORMATION ==="
        echo "OS: $env:OS"
        echo "Processor: $env:PROCESSOR_ARCHITECTURE"
        echo "User: $env:USERNAME"
        echo "PowerShell Version: $($PSVersionTable.PSVersion)"
        echo "Current Time: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')"
        echo "=============================="

        # Check SSH availability
        try {
          $sshVersion = ssh -V 2>&1
          echo "SSH Version: $sshVersion"
        } catch {
          echo "WARNING: SSH not found, attempting to install OpenSSH..."
          try {
            Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
            echo "✓ OpenSSH Client installed"
          } catch {
            echo "✗ Failed to install OpenSSH: $_"
            exit 1
          }
        }

    - name: Enhanced RDP Configuration
      run: |
        echo "=== RDP CONFIGURATION ==="
        echo "Configuring Windows Remote Desktop with enhanced security..."

        try {
          # Enable Remote Desktop
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          echo "✓ Remote Desktop enabled"

          # Configure firewall rules
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          echo "✓ Firewall rules configured"

          # Disable Network Level Authentication (can cause issues with tunneled connections)
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 0
          echo "✓ Network Level Authentication disabled for better tunnel compatibility"

          # Set security layer to RDP Security Layer
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "SecurityLayer" -Value 0
          echo "✓ Security layer set to RDP"

          # Set encryption level to low for better compatibility
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "MinEncryptionLevel" -Value 1
          echo "✓ Encryption level set for compatibility"

          # Configure user account
          $username = "runneradmin"
          $password = "P@ssw0rd!"
          Set-LocalUser -Name $username -Password (ConvertTo-SecureString -AsPlainText $password -Force)
          echo "✓ User credentials configured"

          # Restart RDP service to apply configuration changes
          echo "Restarting RDP service to apply configuration..."
          Restart-Service -Name "TermService" -Force
          Start-Sleep -Seconds 3

          # Verify RDP service
          $rdpService = Get-Service -Name "TermService"
          if ($rdpService.Status -eq "Running") {
            echo "✓ RDP service restarted and running"
          } else {
            echo "⚠ RDP service not running, attempting to start..."
            Start-Service -Name "TermService"
            Start-Sleep -Seconds 2
            $rdpService = Get-Service -Name "TermService"
            if ($rdpService.Status -eq "Running") {
              echo "✓ RDP service started successfully"
            } else {
              echo "✗ Failed to start RDP service"
            }
          }

          # Check if RDP port is listening
          Start-Sleep -Seconds 2  # Give service time to bind to port
          $rdpPort = Get-NetTCPConnection -LocalPort 3389 -ErrorAction SilentlyContinue
          if ($rdpPort) {
            echo "✓ RDP port 3389 is listening"
            echo "  Listening on: $($rdpPort.LocalAddress):$($rdpPort.LocalPort)"
          } else {
            echo "⚠ RDP port 3389 not detected"
            echo "Checking all listening ports..."
            Get-NetTCPConnection -State Listen | Where-Object {$_.LocalPort -eq 3389} | ForEach-Object {
              echo "  Found RDP port: $($_.LocalAddress):$($_.LocalPort)"
            }
          }

          # Additional diagnostics
          echo "=== RDP DIAGNOSTICS ==="
          echo "Current RDP configuration:"
          $rdpConfig = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp'
          echo "  UserAuthentication: $($rdpConfig.UserAuthentication)"
          echo "  SecurityLayer: $($rdpConfig.SecurityLayer)"
          echo "  MinEncryptionLevel: $($rdpConfig.MinEncryptionLevel)"

          $tsConfig = Get-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
          echo "  fDenyTSConnections: $($tsConfig.fDenyTSConnections)"

          echo "=== RDP CONFIGURATION COMPLETE ==="

        } catch {
          echo "✗ RDP configuration failed: $_"
          echo "This may cause connection issues"
        }

    - name: Create Serveo Tunnel
      run: |
        echo "=== SERVEO TUNNEL SETUP ==="
        echo "Starting Serveo tunnel for RDP access..."
        echo "Subdomain: auto-generated"

        try {
          # Direct PuTTY/Plink tunnel creation (inline)
          Write-Host "Creating Serveo tunnel with PuTTY/Plink..." -ForegroundColor Yellow

          # Find or install Plink
          $plinkPath = $null
          $possiblePaths = @("plink.exe", "plink", "C:\Program Files\PuTTY\plink.exe", "C:\Program Files (x86)\PuTTY\plink.exe")

          foreach ($path in $possiblePaths) {
            try {
              $result = & $path -V 2>&1
              if ($LASTEXITCODE -eq 0 -or $result -match "plink|PuTTY") {
                $plinkPath = $path
                Write-Host "✓ Found Plink at: $path" -ForegroundColor Green
                break
              }
            } catch { }
          }

          if (-not $plinkPath) {
            Write-Host "Installing PuTTY..." -ForegroundColor Yellow
            $puttyUrl = "https://the.earth.li/~sgtatham/putty/latest/w64/putty.zip"
            Invoke-WebRequest -Uri $puttyUrl -OutFile "putty.zip" -UseBasicParsing
            Expand-Archive -Path "putty.zip" -DestinationPath "putty" -Force
            Remove-Item "putty.zip" -Force
            $plinkPath = "putty\plink.exe"
            Write-Host "✓ PuTTY installed" -ForegroundColor Green
          }

          # Build Serveo command
          $tunnelSpec = "0:localhost:3389"
          $args = @(
            "-ssh", "-batch", "-T",
            "-o", "StrictHostKeyChecking=no",
            "-o", "UserKnownHostsFile=NUL",
            "-o", "ServerAliveInterval=30",
            "-o", "ConnectTimeout=20",
            "-R", $tunnelSpec,
            "serveo.net"
          )

          Write-Host "Command: $plinkPath $($args -join ' ')" -ForegroundColor Gray

          # Start tunnel process
          $psi = New-Object System.Diagnostics.ProcessStartInfo
          $psi.FileName = $plinkPath
          $psi.Arguments = $args -join " "
          $psi.UseShellExecute = $false
          $psi.RedirectStandardOutput = $true
          $psi.RedirectStandardError = $true
          $psi.CreateNoWindow = $true

          $process = [System.Diagnostics.Process]::Start($psi)
          Write-Host "✓ Plink process started (PID: $($process.Id))" -ForegroundColor Green

          # Monitor for tunnel URL
          $tunnelUrl = $null
          $timeout = 60
          $startTime = Get-Date

          while ((Get-Date) -lt $startTime.AddSeconds($timeout) -and -not $process.HasExited -and -not $tunnelUrl) {
            if (-not $process.StandardOutput.EndOfStream) {
              $line = $process.StandardOutput.ReadLine()
              if ($line) {
                Write-Host "SSH: $line" -ForegroundColor Gray

                if ($line -match "Forwarding TCP connections from ([a-zA-Z0-9\-\.]+\.serveo\.net):(\d+)") {
                  $tunnelUrl = "tcp://$($matches[1]):$($matches[2])"
                  Write-Host "✓ Tunnel URL found: $tunnelUrl" -ForegroundColor Green
                  break
                }
              }
            }
            Start-Sleep -Milliseconds 500
          }

          if ($tunnelUrl) {
            # Save connection details
            $connectionDetails = @{
              tunnelUrl = $tunnelUrl
              provider = "serveo"
              username = "runneradmin"
              password = "P@ssw0rd!"
              timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC"
              method = "putty-inline"
            }

            $connectionDetails | ConvertTo-Json | Out-File -FilePath "connection-details.json" -Encoding UTF8
            Write-Host "✓ Connection details saved" -ForegroundColor Green

            Write-Host "🎉 SERVEO TUNNEL ACTIVE!" -ForegroundColor Green
            Write-Host "Tunnel URL: $tunnelUrl" -ForegroundColor Cyan
            Write-Host "Username: runneradmin" -ForegroundColor Cyan
            Write-Host "Password: P@ssw0rd!" -ForegroundColor Cyan
          } else {
            throw "No tunnel URL found within timeout period"
          }

        } catch {
          Write-Host "✗ Serveo tunnel failed: $_" -ForegroundColor Red
          
          Write-Host "Attempting failover to alternative providers..." -ForegroundColor Yellow

          # Try simple SSH fallback with Serveo
          Write-Host "Trying simple SSH fallback with Serveo..." -ForegroundColor Yellow
          try {
            $sshArgs = @(
              "-o", "StrictHostKeyChecking=no",
              "-o", "UserKnownHostsFile=/dev/null",
              "-o", "ServerAliveInterval=30",
              "-o", "ConnectTimeout=15",
              "-T", "-R", "0:localhost:3389",
              "serveo.net"
            )

            $sshProcess = Start-Process -FilePath "ssh" -ArgumentList $sshArgs -PassThru -NoNewWindow -RedirectStandardOutput "serveo-output.txt" -RedirectStandardError "serveo-error.txt"

            Start-Sleep -Seconds 20

            if (Test-Path "serveo-output.txt") {
              $serveoOutput = Get-Content "serveo-output.txt" -Raw
              if ($serveoOutput -match "Forwarding TCP connections from ([^\s\r\n]+)") {
                $fallbackUrl = "tcp://$($matches[1])"
                Write-Host "✓ SSH fallback successful: $fallbackUrl" -ForegroundColor Green

                $connectionDetails = @{
                  tunnelUrl = $fallbackUrl
                  provider = "serveo-ssh-fallback"
                  username = "runneradmin"
                  password = "P@ssw0rd!"
                  timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC"
                  method = "ssh-fallback"
                }

                $connectionDetails | ConvertTo-Json | Out-File -FilePath "connection-details.json" -Encoding UTF8
                Write-Host "Tunnel URL: $fallbackUrl" -ForegroundColor Cyan
                Write-Host "Username: runneradmin" -ForegroundColor Cyan
                Write-Host "Password: P@ssw0rd!" -ForegroundColor Cyan
                exit 0
              }
            }
          } catch {
            Write-Host "✗ SSH fallback failed: $_" -ForegroundColor Red
          }

          Write-Host "✗ All tunnel providers failed" -ForegroundColor Red
          exit 1
        }
    - name: Keep RDP Server Active
      run: |
        echo "=== RDP SERVER ACTIVE ==="
        echo "RDP server is now running and accessible"
        echo "Session will remain active for the duration of this workflow"
        echo "Maximum session time: 90 minutes (GitHub Actions limit)"
        echo ""
        echo "Connection established at: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')"
        echo "Estimated session end: $(Get-Date -Date (Get-Date).AddMinutes(85) -Format 'yyyy-MM-dd HH:mm:ss UTC')"
        echo ""
        echo "Keeping session alive..."

        # Keep alive with periodic status updates
        $startTime = Get-Date
        $maxDuration = 85 * 60  # 85 minutes in seconds
        $updateInterval = 300   # 5 minutes

        while ((Get-Date) -lt $startTime.AddSeconds($maxDuration)) {
          Start-Sleep -Seconds $updateInterval
          $elapsed = [math]::Round(((Get-Date) - $startTime).TotalMinutes, 1)
          $remaining = [math]::Round(85 - $elapsed, 1)
          echo "Session active for $elapsed minutes, $remaining minutes remaining"

          # Verify RDP service is still running
          $rdpService = Get-Service -Name "TermService" -ErrorAction SilentlyContinue
          if ($rdpService -and $rdpService.Status -eq "Running") {
            echo "✓ RDP service healthy"
          } else {
            echo "⚠ RDP service issue detected"
          }
        }

        echo "Session time limit reached, workflow ending"